/*
 ********************************************************************
 * Licensed Materials - Property of HCL                             *
 *                                                                  *
 * Copyright HCL Technologies Ltd. 2024, 2025. All Rights Reserved. *
 *                                                                  *
 * Note to US Government Users Restricted Rights:                   *
 *                                                                  *
 * Use, duplication or disclosure restricted by GSA ADP Schedule    *
 ********************************************************************
 */

export enum ICON_ITEM_TYPE {
  APPLICATION = 'application',
  BLOG = 'blog',
  CATALOG = 'catalog',
  CHARACTER_WHOLE_NUMBER = 'character--whole-number',
  COLLABORATE = 'collaborate',
  CONTENT_ITEM = 'content--item',
  COPY_FILE = 'copy--file',
  DATA_ANALYTICS = 'data-analytics',
  DATA_BASE = 'data--base',
  DECISION_TREE = 'decision-tree',
  DIAGRAM = 'diagram',
  DOC = 'doc',
  DOCX = 'docx',
  DOCUMENT_BLANK = 'document--blank',
  DOCUMENT_EXPORT = 'document--export',
  EVENT_SCHEDULE = 'event--scheudule',
  EVENT_WARNING = 'event--warning',
  FLOW_DATA = 'flow--data',
  FOLDER_DETAILS_1 = 'folder--details-1',
  FOLDER_DETAILS_2 = 'folder--details-2',
  FOLDER_DETAILS_3 = 'folder--details-3',
  FOLDER_DETAILS = 'folder--details',
  FOLDER = 'folder',
  GIF = 'gif',
  HTML = 'HTML',
  IMAGE_1 = 'image-1',
  IMAGE = 'image',
  INVENTORY_MANAGEMENT = 'inventory-management',
  JPG = 'jpg',
  LAYERS_EXTERNAL = 'layers--external',
  LICENSE_DRAFT='license--draft',
  LICENSE_GLOBAL='license--global',
  LIST_BOXES = 'list--boxes',
  LIST_DROPDOWN = 'list--dropdown',
  MAIL_ALL='mail--all',
  MENU = 'menu',
  MP4 = 'mp4',
  NOTEBOOK_REFERENCE='notebook-reference',
  OGV = 'ogv',
  PAGE_ELEMENTS_RICH_TEXT = 'page--lelments--rich-text',
  PAGE_ELEMENTS_SHORT_TEXT = 'page--lelments--short-text',
  PAGE_ELEMENTS_TEXT = 'page--lelments--text',
  PAGE_SCROLL = 'page-scroll',
  PARENT_CHILD = 'parent-child',
  PDF = 'pdf',
  PNG = 'png',
  PORTFOLIO = 'portfolio',
  PPT = 'ppt',
  PPTX = 'pptx',
  REMINDER = 'reminder',
  SCRIPT = 'script',
  SEARCH_LOCATE = 'search--locate',
  SUBFLOW = 'subflow',
  SVG = 'svg',
  TAG_GROUP = 'tag--group',
  TAG = 'TAG',
  TEMPLATE_1 = 'template-1',
  TEMPLATE = 'template',
  TEXT_LINK = 'text-link',
  TIF = 'tiff',
  USER_PROFILE='user--profile',
  USER_PROFILE_ALT='user--profile--alt',
  VIDEO = 'video',
  WEBM = 'webm',
  WEBP = 'webp',
  XLS = 'xls',
  XLSX = 'xlsx'
}
